In [1]:
import pandas as pd

In [2]:
loc = 'C:\\Users\\Pratt\\Desktop\\HKUST-RA\\Database Construction P2\\Web.csv'

In [3]:
df = pd.read_csv(loc)

In [4]:
unique_df = df.drop_duplicates(subset='gvkey')
unique_df.reset_index(drop=True, inplace=True)

part 2

In [5]:
new_loc = 'C:\\Users\\Pratt\\Desktop\\HKUST-RA\\Database Construction P2\\current.csv'

In [6]:
current_df = pd.read_csv(new_loc)

In [7]:
unique_current_df  = current_df.drop_duplicates(subset='gvkey')
unique_current_df.reset_index(drop=True, inplace=True)

In [8]:
unique_current_df

    indexname   gvkey   tic                     companyname
0     S&P 500    7435   MMM                      3M Company
1     S&P 500    9771   AOS         A. O. Smith Corporation
2     S&P 500    1598   AME                    AMETEK, Inc.
3     S&P 500    1678   APA                 APA Corporation
4     S&P 500    9899     T                       AT&T Inc.
..        ...     ...   ...                             ...
495   S&P 500   24405  ZBRA  Zebra Technologies Corporation
496   S&P 500  144559   ZBH    Zimmer Biomet Holdings, Inc.
497   S&P 500   13721   ZTS                     Zoetis Inc.
498   S&P 500  114524  EBAY                       eBay Inc.
499   S&P 500  178015  LULU        lululemon athletica inc.

[500 rows x 4 columns]

In [9]:
unique_df

,costat,curcd,datafmt,indfmt,consol,gvkey,datadate,conm,tic,weburl
0,A,USD,STD,INDL,C,1075,2010-12-31,PINNACLE WEST CAPITAL CORP,PNW,www.pinnaclewest.com
1,A,USD,STD,INDL,C,1078,2010-12-31,ABBOTT LABORATORIES,ABT,www.abbott.com
2,A,USD,STD,INDL,C,1161,2010-12-31,ADVANCED MICRO DEVICES,AMD,www.amd.com
3,A,USD,STD,INDL,C,1209,2010-09-30,AIR PRODUCTS & CHEMICALS INC,APD,www.airproducts.com
4,A,USD,STD,INDL,C,1300,2010-12-31,HONEYWELL INTERNATIONAL INC,HON,www.honeywell.com
...,...,...,...,...,...,...,...,...,...,...
495,A,USD,STD,INDL,C,189491,2010-12-31,XYLEM INC,XYL,www.xylem.com
496,A,USD,STD,FS,C,260774,2010-12-31,CBRE GROUP INC,CBRE,www.cbre.com
497,A,USD,STD,INDL,C,283184,2022-12-31,SMURFIT WESTROCK PLC,SW,www.smurfitwestrock.com
498,A,USD,STD,INDL,C,294524,2010-12-31,LYONDELLBASELL INDUSTRIES,LYB,www.lyondellbasell.com
499,A,USD,STD,INDL,C,316056,2011-12-31,ALLEGION PLC,ALLE,www.allegion.com/corp/en/index.html

In [10]:
merged = unique_df.merge(unique_current_df, on='gvkey', how='inner')

In [11]:
merged

,costat,curcd,datafmt,indfmt,consol,gvkey,datadate,conm,tic_x,weburl,indexname,tic_y,companyname
0,A,USD,STD,INDL,C,1075,2010-12-31,PINNACLE WEST CAPITAL CORP,PNW,www.pinnaclewest.com,S&P 500,PNW,Pinnacle West Capital Corporation
1,A,USD,STD,INDL,C,1078,2010-12-31,ABBOTT LABORATORIES,ABT,www.abbott.com,S&P 500,ABT,Abbott Laboratories
2,A,USD,STD,INDL,C,1161,2010-12-31,ADVANCED MICRO DEVICES,AMD,www.amd.com,S&P 500,AMD,"Advanced Micro Devices, Inc."
3,A,USD,STD,INDL,C,1209,2010-09-30,AIR PRODUCTS & CHEMICALS INC,APD,www.airproducts.com,S&P 500,APD,"Air Products and Chemicals, Inc."
4,A,USD,STD,INDL,C,1300,2010-12-31,HONEYWELL INTERNATIONAL INC,HON,www.honeywell.com,S&P 500,HON,Honeywell International Inc.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,A,USD,STD,INDL,C,189491,2010-12-31,XYLEM INC,XYL,www.xylem.com,S&P 500,XYL,Xylem Inc.
496,A,USD,STD,FS,C,260774,2010-12-31,CBRE GROUP INC,CBRE,www.cbre.com,S&P 500,CBRE,"CBRE Group, Inc."
497,A,USD,STD,INDL,C,283184,2022-12-31,SMURFIT WESTROCK PLC,SW,www.smurfitwestrock.com,S&P 500,SW,Smurfit Westrock Plc
498,A,USD,STD,INDL,C,294524,2010-12-31,LYONDELLBASELL INDUSTRIES,LYB,www.lyondellbasell.com,S&P 500,LYB,LyondellBasell Industries N.V.
499,A,USD,STD,INDL,C,316056,2011-12-31,ALLEGION PLC,ALLE,www.allegion.com/corp/en/index.html,S&P 500,ALLE,Allegion plc

In [12]:
import json

json_data = merged[['companyname', 'weburl']].to_dict(orient='records')

output_path = 'C:\\Users\\Pratt\\Desktop\\HKUST-RA\\Database Construction P2\\company_weburl.json'
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(json_data, f, ensure_ascii=False, indent=2)

print(f"JSON 文件已保存到: {output_path}")
print(f"共 {len(json_data)} 条记录")

JSON 文件已保存到: C:\Users\Pratt\Desktop\HKUST-RA\Database Construction P2\company_weburl.json
共 500 条记录